config/routes.rb
# -*- encoding : utf-8 -*-
require 'sidekiq/web'

Pathfinder::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope controller: 'site' do
    get '/', action: 'index', as: 'home'
    match '/login', action: 'login', as: 'login', via: ['get','post']
    get '/logout', action: 'logout'
    post '/generate', action: 'generate', as: 'generate_cache'
  end

  namespace 'account' do
    scope '/profile', controller: 'profile' do
      get '/', action: 'index', as: 'profile'
      match '/edit', action: 'edit', as: 'edit_profile', via:[:get,:post]
      match '/change_password', action: 'change_password', as: 'change_password', via:[:get,:post]
    end
  end

  namespace 'admin' do
    scope '/users', controller: 'users' do
      get '/', action: 'index', as: 'users'
      get '/show/:id', action: 'show', as: 'user'
      match '/new', action: 'new', as: 'new_user', via: ['get','post']
      match '/edit/:id', action: 'edit', as: 'edit_user', via: ['get','post']
      delete '/delete/:id', action: 'destroy', as: 'destroy_user'
      match '/add_region/:id', action: 'add_region', as: 'user_add_region', via: ['get', 'post']
      delete '/remove_region/:id', action: 'remove_region', as: 'user_remove_region'
    end
    scope 'help', controller: 'help' do
      get '/', action: 'index', as: 'help'
    end
  end

  scope '/regions', controller: 'regions' do
    get '/', action: 'index', as: 'regions'
    get '/show/:id', action: 'show', as: 'region'
    match '/new', action: 'new', as: 'new_region', via: [:get, :post]
    match '/edit/:id', action: 'edit', as: 'edit_region', via: [:get, :post]
    delete '/delete/:id', action: 'delete', as: 'delete_region'
  end

  namespace 'objects' do
    scope '/towers', controller: 'towers' do
      get '/', action: 'index', as: 'towers'
      get '/show/:id', action: 'show', as: 'tower'
      match '/upload', action: 'upload', via: ['get','post'], as: 'upload_towers'
      match '/upload_photo/:id', action: 'upload_photo', via: ['get', 'post'], as: 'upload_tower_photo'
      delete '/delete_photo/:id', action: 'delete_photo', as: 'delete_tower_photo'
    end
    scope '/offices', controller: 'offices' do
      get '/', action: 'index', as: 'offices'
      get '/show/:id', action: 'show', as: 'office'
      match '/upload', action: 'upload', via: ['get', 'post'], as: 'upload_offices'
    end
    scope '/substations', controller: 'substations' do
      get '/', action: 'index', as: 'substations'
      get '/show/:id', action: 'show', as: 'substation'
      match '/upload', action: 'upload', via: ['get', 'post'], as: 'upload_substations'
    end
    scope '/lines', controller: 'lines' do
      get '/', action: 'index', as: 'lines'
      get '/show/:id', action: 'show', as: 'line'
      match '/upload', action: 'upload', via: ['get','post'], as: 'upload_lines'
    end
    scope '/maps', controller: 'maps' do
      get '/editor', action: 'editor', as: 'map_editor'
      get '/viewer', action: 'viewer', as: 'map_viewer'
      get '/viewer2', action: 'viewer2'
      match 'generate_images', action: 'generate_images', as: 'generate_images', via: ['get', 'post']
    end
    scope '/path' do
      scope '/lines', controller: 'path_lines' do
        get '/', action: 'index', as: 'path_lines'
        get '/show/:id', action: 'show', as: 'path_line'
        match '/upload', action: 'upload', via: ['get','post'], as: 'upload_path_lines'
      end
      scope '/types', controller: 'path_types' do
        get '/', action: 'index', as: 'path_types'
        get '/show/:id', action: 'show', as: 'path_type'
        match '/new', action: 'new', as: 'new_path_type', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_type', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_type'
        post '/up/:id', action: 'up', as: 'up_path_type'
        post '/down/:id', action: 'down', as: 'down_path_type'
      end
      scope '/surfaces', controller: 'path_surfaces' do
        get '/', action: 'index', as: 'path_surfaces'
        get '/show/:id', action: 'show', as: 'path_surface'
        match '/new', action: 'new', as: 'new_path_surface', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_surface', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_surface'
        post '/up/:id', action: 'up', as: 'up_path_surface'
        post '/down/:id', action: 'down', as: 'down_path_surface'
      end
      scope '/details', controller: 'path_details' do
        get '/', action: 'index', as: 'path_details'
        get '/show/:id', action: 'show', as: 'path_detail'
        match '/new', action: 'new', as: 'new_path_detail', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_detail', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_detail'
        post '/up/:id', action: 'up', as: 'up_path_detail'
        post '/down/:id', action: 'down', as: 'down_path_detail'
      end
    end
    scope '/photos', controller: 'photos' do
      get '/', action: 'index', as: 'photos'
      get '/all', action: 'all', as: 'all_photos'
      post '/confirm/:id', action: 'confirm', as: 'confirm_photo'
    end
  end

  namespace 'tasks' do
    scope '/', controller: 'base' do
      get '/open', action: 'open', as: 'open'
      get '/all', action: 'all', as: 'all'
      get '/show/:id', action: 'show', as: 'task'
      match '/edit/:id', action: 'edit', as: 'edit_task', via: ['get', 'post']
      delete '/delete/:id', action: 'destroy', as: 'delete_task'
      post '/begin/:id', action: 'begin_task', as: 'begin_task'
      post '/cancel/:id', action: 'cancel_task', as: 'cancel_task'
      post '/complete/:id', action: 'complete_task', as: 'complete_task'
    end
    scope 'tracking', controller: 'tracking' do
      get '/', action: 'index', as: 'tracking'
      get '/user/:id', action: 'user', as: 'tracking_user'
      get '/track/:id', action: 'track', as: 'tracking_track'
    end
  end

  namespace 'api' do
    scope '/users', controller: 'users' do
      get '/', action: 'index'
      post '/login', action: 'login'
      post '/track_point', action: 'track_point'
    end
    scope '/objects', controller: 'objects' do
      get '/', action: 'index'
      get '/lines', action: 'lines'
      get '/pathlines', action: 'pathlines'
      get '/offices', action: 'offices'
      get '/substations', action: 'substations'
      get '/towers', action: 'towers'
    end
    scope '/paths', controller: 'paths' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
      get '/details', action: 'details'
    end
    scope '/lines', controller: 'lines' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'towers', controller: 'towers' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
      post '/upload_photo', action: 'upload_photo'
    end
    scope 'offices', controller: 'offices' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'substations', controller: 'substations' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'shortestpath', controller: 'shortestpath' do
      get '/', action: 'index'
    end
    scope 'tasks', controller: 'tasks' do
      match '/', action: 'index', via: ['get', 'post']
      post '/new', action: 'new'
      post '/begin_task', action: 'begin_task'
      post '/complete_task', action: 'complete_task'
      post '/cancel_task', action: 'cancel_task'
      post '/add_note', action: 'add_note'
    end
  end

  root 'site#index'
end

app/models/tracking/point.rb
# -*- encoding : utf-8 -*-
class Tracking::Point
  include Mongoid::Document
  include Mongoid::Timestamps
  include Objects::Coordinate
  belongs_to :path, class_name: 'Tracking::Path'
end

app/controllers/api/tasks_controller.rb
# -*- encoding : utf-8 -*-
require 'json'

class Api::TasksController < ApiController
  def index
    authenticate do |user|
      @tasks = Task.open_tasks.where(assignee: user).desc(:_id).paginate(per_page: 10, page: params[:page])
    end
  end

  def new
    assignee = Sys::User.find(params[:assignee_id])
    destinations = params[:destinations].map{|k,v| v} if params[:destinations]
    paths = params[:paths].map{|k,v| v.map{|k,v| v }} if params[:paths]
    task = Task.create(assignee: assignee, note: params[:note], paths: paths, destinations: destinations)
    render json: {number: task.number}
  end

  def begin_task
    task = Task.find(params[:id])
    if task.can_begin?
      task.begin ; render json: { text: 'ok' }
    else
      render json: { error: 'ამ დავალებას ვერ დაიწყებთ: ჯერ დახურეთ სხვა დავალებები.' }
    end
  end

  def cancel_task
    task = Task.find(params[:id])
    if task.can_cancel?
      task.cancel ; render json: { text: 'ok' }
    else
      render json: { error: 'ამ დავალებას ვერ გააუქმებთ' }
    end
  end

  def complete_task
    task = Task.find(params[:id])
    if task.can_cancel?
      task.complete ; render json: { text: 'ok' }
    else
      render json: { error: 'ამ დავალებას ვერ დაასრულებთ' }
    end
  end

  def add_note
    task = Task.find(params[:id]) ; detail = Objects::Path::Detail.find(params[:detail_id])
    note = Objects::Note.create(task: task, detail: detail, lat: params[:lat].to_f, lng: params[:lng].to_f, text: params[:note])
    render json: { status: 'ok' }
  end
end

app/controllers/tasks/base_controller.rb
# -*- encoding : utf-8 -*-
class Tasks::BaseController < ApplicationController
  def open
    @title='ღია დავალებები'
    @tasks = Task.open_tasks.desc(:_id).paginate(page: params[:page], per_page: 10)
  end

  def all
    @title='ყველა დავალება'
    rel = Task
    @search = search_params
    if @search.present?
      rel = rel.where(number: @search[:number]) if @search[:number].present?
      rel = rel.where(assignee_id: @search[:assignee_id]) if @search[:assignee_id].present?
      rel = rel.where(status: @search[:status]) if @search[:status].present?
    end
    @tasks = rel.desc(:_id).paginate(page: params[:page], per_page: 10)
  end

  def show
    @title='დავალების თვისებები'
    @task = Task.find(params[:id])
    respond_to do |format|
      format.html
      format.kmz { send_data @task.to_kmz(as: params[:as]), filename: "task-#{params[:as]}-##{@task.number}.kmz" }
    end
  end

  def edit
    @title='რედაქტირება'
    @task = Task.find(params[:id])
    if request.post?
      if @task.update_attributes(params.require(:task).permit(:note, :assignee_id))
        redirect_to tasks_task_url(id: @task.id), notice: 'დავალება შეცვლილია'
      end
    end
  end

  def destroy
    task = Task.find(params[:id])
    if task.can_delete?
      task.destroy
      redirect_to tasks_open_url, notice: 'დავალება წაშლილია'
    else
      redirect_to tasks_task_url(id: task.id), alert: 'ამ დავალებას ვერ წავშლი'
    end
  end

  def begin_task
    task = Task.find(params[:id])
    if task.can_begin?
      task.begin
      redirect_to tasks_task_url(id: task.id), notice: 'დავალება დაწყებულია'
    else
      redirect_to tasks_task_url(id: task.id), alert: 'დავალებას ვერ დავიწყებ'
    end
  end

  def cancel_task
    task = Task.find(params[:id])
    if task.can_cancel?
      task.cancel
      redirect_to tasks_task_url(id: task.id), notice: 'დავალება გაუქმებულია'
    else
      redirect_to tasks_task_url(id: task.id), alert: 'დავალებას ვერ გავაუქმებ'
    end
  end

  def complete_task
    task = Task.find(params[:id])
    if task.can_cancel?
      task.complete
      redirect_to tasks_task_url(id: task.id), notice: 'დავალება დასრულებულია'
    else
      redirect_to tasks_task_url(id: task.id), alert: 'დავალებას ვერ დავასრულებ'
    end
  end

  protected
  def nav
    @nav=super
    @nav['ღია დავალებები']=tasks_open_url
    unless ['open'].include?(action_name)
      @nav['ყველა დავალება']=tasks_all_url unless ['all'].include?(action_name)
      @nav["დავალება ##{@task.number}"]=tasks_task_url(id:@task.id) if (@task and not [ 'show' ].include?(action_name))
      @nav[@title]=nil
    end
  end

  def login_required; true end
  def permission_required; false end
end

app/controllers/tasks/tracking_controller.rb
# -*- encoding : utf-8 -*-
class Tasks::TrackingController < ApplicationController
  def index
    @title = 'მომხმარებელთა ტრეკინგი'
    @users = Sys::User.all.asc(:username)
    @last_tracks = @users.map{|user| Tracking::Path.where(user: user).last }.compact
  end

  def user
    @user=Sys::User.find(params[:id])
    @title=@user.full_name
    @tracks=Tracking::Path.where(user:@user).desc(:_id).paginate(per_page: 10, page: params[:page])
  end

  def track
    @track = Tracking::Path.find(params[:id])
    respond_to do |format|
      format.html do
        @user = @track.user
        @title = @track.description
      end
      format.kml { render text: @track.to_kml }
      format.kmz { send_data @track.to_kmz, filename: "track-#{@track.user.username}-#{@track.created_at.strftime('%Y%m%d')}.kmz" }
    end
  end

  protected
  def nav
    @nav=super
    @nav['მომხმარებელთა ტრეკინგი']=tasks_tracking_url
    @nav[@track.user.full_name]=tasks_tracking_user_url(id:@track.user) if @track
    @nav[@title]=nil unless ['index'].include?(action_name)
  end

  def login_required; true end
  def permission_required; false end
end

app/helpers/tasks_helper.rb
# -*- encoding : utf-8 -*-
module TasksHelper
  def tasks_table(tasks, opts={})
    table_for tasks, title: opts[:title]||'დავალებები', icon: '/icons/report-paper.png', collapsible: true do |t|
      t.edit_action ->(x){ tasks_edit_task_url(id: x.id) }
      t.delete_action ->(x){ tasks_delete_task_url(id: x.id) }, condition: ->(x){ x.can_delete? }
      t.text_field 'number', tag: 'code'
      t.date_field 'created_at', url: ->(x){ tasks_task_url(id:x.id) }, turbolink: false
      t.text_field 'status_name', i18n: 'status', icon: ->(x){ x.status_icon }
      t.text_field 'note'
      t.complex_field i18n: 'assignee' do |t|
        t.text_field 'assignee.username', tag: 'strong', url: ->(x){ admin_user_url(id: x.assignee.id) }
        t.text_field 'assignee.full_name'
      end
      t.paginate records: 'ჩანაწერი'
    end
  end

  def task_view(task, opts={})
    selected_tab = case opts[:tab] when 'sys' then 2 when 'notes' then 1 else 0 end
    view_for task, title: 'დავალების თვისებები', icon: '/icons/report-paper.png', collapsible: true, selected_tab: selected_tab do |f|
      f.edit_action tasks_edit_task_url(id: task.id)
      f.delete_action tasks_delete_task_url(id: task.id), condition: ->(x){ x.can_delete? }
      f.tab title: 'ძირითადი', icon: '/icons/report-paper.png' do |f|
        f.text_field 'number', required: true, tag: 'code'
        f.date_field 'created_at', required: true
        f.text_field 'status_name', required: true, i18n: 'status', icon: ->(x){ x.status_icon } do |f|
          f.action tasks_begin_task_url(id: task.id), label: 'დავალების დაწყება', icon: '/icons/status_in_progress.png', method: 'post', confirm: 'ნამდვილად გინდათ დავალების დაწყება?' if task.can_begin?
          f.action tasks_complete_task_url(id: task.id), label: 'დავალების დასრულება', icon: '/icons/status_completed.png', method: 'post', confirm: 'ნამდვილად გინდათ დავალების დასრულება?' if task.can_complete?
          f.action tasks_cancel_task_url(id: task.id), label: 'დავალების გაუქმება', icon: '/icons/status_canceled.png', method: 'post', confirm: 'ნამდვილად გინდათ დავალების გაუქმება?' if task.can_cancel?
        end
        f.complex_field i18n: 'assignee', required: true do |f|
          f.text_field 'assignee.username', tag: 'strong', url: admin_user_url(id: task.assignee.id)
          f.text_field 'assignee.full_name'
        end
        f.text_field 'note'
      end
      f.tab title: 'შენიშვნები', icon: '/icons/sticky-note.png' do |t|
        t.table_field 'notes', table: { title: 'შენიშვნები', icon: '/icons/sticky-note.png' } do |field|
          field.table do |t|
            t.text_field 'text'
            t.complex_field label: 'საფარი' do |c|
              c.text_field 'detail.surface.type.name', after: '&rarr;'.html_safe, url: ->(x){ objects_path_type_url(id: x.detail.surface.type.id) }
              c.text_field 'detail.surface.name', after: '&rarr;'.html_safe, url: ->(x){ objects_path_surface_url(id: x.detail.surface.id) }
              c.text_field 'detail.name', tag: 'strong', url: ->(x){ objects_path_detail_url(id: x.detail.id) }
            end
            t.complex_field label: 'კოორდინატები' do |c|
              c.text_field 'easting', tag: 'code', before: 'E:'
              c.text_field 'northing', tag: 'code', before: 'N:'
            end
          end
        end
      end
      f.tab title: 'სისტემური',icon:'/icons/traffic-cone.png' do |f|
        f.timestamps
      end
    end
  end

  def task_form(task, opts={})
    title=opts[:title]
    icon='/icons/report-paper.png'
    forma_for task, title: title, icon: icon, collapsible: true do |f|
      f.combo_field 'assignee_id', collection: Sys::User.where(active: true), empty: false, i18n: 'assignee', required: true
      f.text_field 'note', width: 600, autofocus: true
      f.submit 'შენახვა'
      f.cancel_button tasks_task_url(id: task.id), turbolink: false
    end
  end
end

app/views/tasks/tracking/_tracks.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>მომხმარებელი</th>
      <th>დავალება</th>
      <th>დასაწყისი</th>
      <th>ბოლო</th>
      <th>წერტილები</th>
    </tr>
  </thead>
  <tbody>
    <% if tracks.any? %>
      <% tracks.each do |track| %>
        <tr>
          <td>
            <img src="/icons/user.png"/>
            <strong><%= track.user.username %></strong>
            (<span class="text-muted"><%= track.user.full_name %></span>)
          </td>
          <td>
            <% if track.task %>
              <img src="<%= track.task.status_icon %>"/>
              #<code><%= link_to track.task.number, tasks_task_url(id: track.task.id), data: {'no-turbolink' => true} %></code>
            <% else %>
              <span class="text-muted">(ცარიელი)</span>
            <% end %>
          </td>
          <td>
            <img src="<%= track.open ? '/icons/clock.png' : '/icons/tick.png' %>"/>
            <%= track.created_at.localtime.strftime('%d-%b-%Y %H:%M:%S') %>
          </td>
          <td><%= track.updated_at.localtime.strftime('%d-%b-%Y %H:%M:%S') %></td>
          <td><code><%= track.points.count%></code> <%= link_to 'წერტილი', tasks_tracking_track_url(id: track.id), data: {'no-turbolink' => true} %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="5" style="padding:32px; text-align: center; background: #eee;">no-data</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate tracks if tracks.respond_to?(:total_pages) %>

app/views/tasks/tracking/index.html.erb
<!-- current tracks -->

<h3 class="page-header">
  <i class="fa fa-send"></i>
  მიმდინარე ტრეკები
</h3>
<%= render partial: '/layouts/paths', locals: {paths: @last_tracks, direction: true} %>
<script type="text/javascript">
  var users = <%= raw @last_tracks.map { |track| last=track.points.last; {username: track.user.username, full_name: track.user.full_name, lat: last.lat, lng: last.lng} if last }.compact.to_json %>;
  var onPostInitialize = function(map, bounds) {
    for(var i = 0, l = users.length; i < l; i++) {
      var user = users[i];
      var position = new google.maps.LatLng(user.lat, user.lng);

      new MarkerWithLabel({
         position: position,
         map: map,
         icon: '/map/user.png',
         labelContent: user.username + ' (' + user.full_name + ')',
         labelAnchor: new google.maps.Point(8, 0),
         labelClass: "map-labels",
         labelStyle: { opacity: 0.75 }
       });
    }
    if (users.length > 1) { map.fitBounds(bounds); }
  };
</script>

<!-- all users -->

<h3 class="page-header">
  <i class="fa fa-users"></i>
  ყველა მომხმარებელი
</h3>
<p class="text-muted">აარჩიეთ სიიდან მომხმარებელი, რომლის ტრეკინგიც გსრუთ.</p>
<table class="table table-bordered table-striped table-hover">
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td width="200"><img src="/icons/user.png"/> <strong><%=user.username%></strong></td>
      <td><%=link_to user.full_name, tasks_tracking_user_url(id: user.id)%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/tracking/track.html.erb
<div class="page-header">
  <div class="pull-right">
    <a href="<%=tasks_tracking_track_url(id:@track.id, format: 'kmz')%>" class="btn btn-default">
      <i class="fa fa-download"></i>
      KMZ ფორმატში
    </a>
  </div>
  <h2><%=@title%></h2>
</div>
<p class="pull-right"><code><%=@track.points.count%></code>წერტილი</p>
<p>
  მომხმარებელი: <img src="/icons/user.png" />
  <strong><%=@track.user.username%></strong>
  <%=link_to @track.user.full_name, tasks_tracking_user_url(id: @track.user.id)%>
</p>

<% if @track.task %>
  <p>
    დავალება:
    <% if @track.task%>
      <img src="<%= @track.task.status_icon %>" />
      #<code><%= link_to @track.task.number, tasks_task_url(id: @track.task.id), data: { 'no-turbolink'=>true } %></code>
    <% end %>
  </p>
<% end %>

<%= render partial: '/layouts/paths', locals: {paths: [ @track ], direction: true} %>
<% last_p = @track.points.last %>
<% if last_p %>
<script type="text/javascript">
  var last_point = <%= raw ({ username: @user.username, full_name: @user.full_name, lat: last_p.lat, lng: last_p.lng }).to_json %>;
  var onPostInitialize = function(map, bounds) {
    var data = last_point;
    new MarkerWithLabel({
       position: new google.maps.LatLng(data.lat, data.lng),
       map: map,
       icon: '/map/user.png',
       labelContent: data.username + ' (' + data.full_name + ')',
       labelAnchor: new google.maps.Point(8, 0),
       labelClass: "map-labels",
       labelStyle: { opacity: 0.75 }
     });
    map.fitBounds(bounds);
  };
</script>
<% end %>

app/views/tasks/tracking/user.html.erb
<h2 class="page-header">
  <code><%= @user.username %></code>
  <%= @user.full_name %>
</h2>
<%= render partial: '/tasks/tracking/tracks', locals: {tracks: @tracks} %>