config/routes.rb
# -*- encoding : utf-8 -*-
require 'sidekiq/web'

Pathfinder::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  scope controller: 'site' do
    get '/', action: 'index', as: 'home'
    match '/login', action: 'login', as: 'login', via: ['get','post']
    get '/logout', action: 'logout'
    post '/generate', action: 'generate', as: 'generate_cache'
  end

  namespace 'account' do
    scope '/profile', controller: 'profile' do
      get '/', action: 'index', as: 'profile'
      match '/edit', action: 'edit', as: 'edit_profile', via:[:get,:post]
      match '/change_password', action: 'change_password', as: 'change_password', via:[:get,:post]
    end
  end

  namespace 'admin' do
    scope '/users', controller: 'users' do
      get '/', action: 'index', as: 'users'
      get '/show/:id', action: 'show', as: 'user'
      match '/new', action: 'new', as: 'new_user', via: ['get','post']
      match '/edit/:id', action: 'edit', as: 'edit_user', via: ['get','post']
      delete '/delete/:id', action: 'destroy', as: 'destroy_user'
      match '/add_region/:id', action: 'add_region', as: 'user_add_region', via: ['get', 'post']
      delete '/remove_region/:id', action: 'remove_region', as: 'user_remove_region'
    end
    scope 'help', controller: 'help' do
      get '/', action: 'index', as: 'help'
    end
  end

  scope '/regions', controller: 'regions' do
    get '/', action: 'index', as: 'regions'
    get '/show/:id', action: 'show', as: 'region'
    match '/new', action: 'new', as: 'new_region', via: [:get, :post]
    match '/edit/:id', action: 'edit', as: 'edit_region', via: [:get, :post]
    delete '/delete/:id', action: 'delete', as: 'delete_region'
  end

  namespace 'objects' do
    scope '/towers', controller: 'towers' do
      get '/', action: 'index', as: 'towers'
      get '/show/:id', action: 'show', as: 'tower'
      match '/upload', action: 'upload', via: ['get','post'], as: 'upload_towers'
      match '/upload_photo/:id', action: 'upload_photo', via: ['get', 'post'], as: 'upload_tower_photo'
      delete '/delete_photo/:id', action: 'delete_photo', as: 'delete_tower_photo'
    end
    scope '/offices', controller: 'offices' do
      get '/', action: 'index', as: 'offices'
      get '/show/:id', action: 'show', as: 'office'
      match '/upload', action: 'upload', via: ['get', 'post'], as: 'upload_offices'
    end
    scope '/substations', controller: 'substations' do
      get '/', action: 'index', as: 'substations'
      get '/show/:id', action: 'show', as: 'substation'
      match '/upload', action: 'upload', via: ['get', 'post'], as: 'upload_substations'
    end
    scope '/lines', controller: 'lines' do
      get '/', action: 'index', as: 'lines'
      get '/show/:id', action: 'show', as: 'line'
      match '/upload', action: 'upload', via: ['get','post'], as: 'upload_lines'
    end
    scope '/maps', controller: 'maps' do
      get '/editor', action: 'editor', as: 'map_editor'
      get '/viewer', action: 'viewer', as: 'map_viewer'
      get '/viewer2', action: 'viewer2'
      match 'generate_images', action: 'generate_images', as: 'generate_images', via: ['get', 'post']
    end
    scope '/path' do
      scope '/lines', controller: 'path_lines' do
        get '/', action: 'index', as: 'path_lines'
        get '/show/:id', action: 'show', as: 'path_line'
        match '/upload', action: 'upload', via: ['get','post'], as: 'upload_path_lines'
      end
      scope '/types', controller: 'path_types' do
        get '/', action: 'index', as: 'path_types'
        get '/show/:id', action: 'show', as: 'path_type'
        match '/new', action: 'new', as: 'new_path_type', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_type', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_type'
        post '/up/:id', action: 'up', as: 'up_path_type'
        post '/down/:id', action: 'down', as: 'down_path_type'
      end
      scope '/surfaces', controller: 'path_surfaces' do
        get '/', action: 'index', as: 'path_surfaces'
        get '/show/:id', action: 'show', as: 'path_surface'
        match '/new', action: 'new', as: 'new_path_surface', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_surface', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_surface'
        post '/up/:id', action: 'up', as: 'up_path_surface'
        post '/down/:id', action: 'down', as: 'down_path_surface'
      end
      scope '/details', controller: 'path_details' do
        get '/', action: 'index', as: 'path_details'
        get '/show/:id', action: 'show', as: 'path_detail'
        match '/new', action: 'new', as: 'new_path_detail', via: ['get','post']
        match '/edit/:id', action: 'edit', as: 'edit_path_detail', via: ['get', 'post']
        delete '/delete/:id', action: 'delete', as: 'delete_path_detail'
        post '/up/:id', action: 'up', as: 'up_path_detail'
        post '/down/:id', action: 'down', as: 'down_path_detail'
      end
    end
    scope '/photos', controller: 'photos' do
      get '/', action: 'index', as: 'photos'
      get '/all', action: 'all', as: 'all_photos'
      post '/confirm/:id', action: 'confirm', as: 'confirm_photo'
    end
  end

  namespace 'tasks' do
    scope '/', controller: 'base' do
      get '/open', action: 'open', as: 'open'
      get '/all', action: 'all', as: 'all'
      get '/show/:id', action: 'show', as: 'task'
      match '/edit/:id', action: 'edit', as: 'edit_task', via: ['get', 'post']
      delete '/delete/:id', action: 'destroy', as: 'delete_task'
      post '/begin/:id', action: 'begin_task', as: 'begin_task'
      post '/cancel/:id', action: 'cancel_task', as: 'cancel_task'
      post '/complete/:id', action: 'complete_task', as: 'complete_task'
    end
    scope 'tracking', controller: 'tracking' do
      get '/', action: 'index', as: 'tracking'
      get '/user/:id', action: 'user', as: 'tracking_user'
      get '/track/:id', action: 'track', as: 'tracking_track'
    end
  end

  namespace 'api' do
    scope '/users', controller: 'users' do
      get '/', action: 'index'
      post '/login', action: 'login'
      post '/track_point', action: 'track_point'
    end
    scope '/objects', controller: 'objects' do
      get '/', action: 'index'
      get '/lines', action: 'lines'
      get '/pathlines', action: 'pathlines'
      get '/offices', action: 'offices'
      get '/substations', action: 'substations'
      get '/towers', action: 'towers'
    end
    scope '/paths', controller: 'paths' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
      get '/details', action: 'details'
    end
    scope '/lines', controller: 'lines' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'towers', controller: 'towers' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
      post '/upload_photo', action: 'upload_photo'
    end
    scope 'offices', controller: 'offices' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'substations', controller: 'substations' do
      get '/show', action: 'show'
      post '/new',  action: 'new'
      post '/edit', action: 'edit'
      post '/delete', action: 'delete'
    end
    scope 'shortestpath', controller: 'shortestpath' do
      get '/', action: 'index'
    end
    scope 'tasks', controller: 'tasks' do
      match '/', action: 'index', via: ['get', 'post']
      post '/new', action: 'new'
      post '/begin_task', action: 'begin_task'
      post '/complete_task', action: 'complete_task'
      post '/cancel_task', action: 'cancel_task'
      post '/add_note', action: 'add_note'
    end
  end

  root 'site#index'
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-
class SiteController < ApplicationController
  def index; @title=t('pages.site.index.title') end

  def login
    @title=t('pages.site.login.title')
    if request.post?
      user=Sys::User.authenticate(params[:username], params[:password])

      if user and user.active
        session[:user_id]=user.id
        redirect_to root_url
      else
         @error=t('pages.site.login.illegal_login')
      end
    end
  end

  def logout
    session[:user_id]=nil
    redirect_to root_url
  end

  def generate
    Sys::Cache.clear_map_objects
    CacheGeneration.perform_async
    redirect_to home_url, notice: 'კეშის გენერაცია დაწყებულია: იხილეთ მიმდინარე დავალებები.'
  end

  protected
  def nav
    @nav = super
    @nav[@title] = nil unless action_name == 'index'
  end

  def login_required; ['index'].include?(action_name) end
  def permission_required; false end
end

app/views/site/index.html.erb
<div>
  <p style="padding-top: 48px;" class="text-center">
    <a class="btn btn-success btn-lg" href="<%=objects_map_viewer_url%>" data-no-turbolink>
      <i class="fa fa-globe"></i> ობიექტების რუკა
    </a>
    <% if current_user.editor %>
      <a class="btn btn-warning btn-lg" href="<%=objects_map_editor_url%>" data-no-turbolink>
        <i class="fa fa-pencil"></i> ობიექტების რედაქტირება
      </a>
    <% end %>
  </p>
</div>
<div class="row">
  <div class="col-sm-6">
    <div>
      <div class="page-header">
        <div class="pull-right">
          <span class="label label-info">ღია</span>
          <span class="label label-danger">სულ</span>
        </div>
        <h3>
          <i class="fa fa-tasks"></i>
          დავალებები
        </h3>
      </div>
      <p>
        <i class="fa fa-tasks"></i>
        <%= link_to 'დავალებები', tasks_open_url %>
        <span class="label label-info"><%= Task.open_tasks.count %></span>
        <span class="label label-danger"><%= Task.count %></span>
      </p>
      <p>
        <i class="fa fa-image"></i>
        <%=link_to 'ფოტოგალერეა', objects_photos_url, data: { 'no-turbolink' => true }%>
        <span class="label label-info"><%= Objects::Photo.not_confirmed.count %></span>
        <span class="label label-danger"><%= Objects::Photo.count %></span>
      </p>
      <p>
        <i class="fa fa-users"></i>
        <%=link_to 'მომხმარებელთა ტრეკინგი', tasks_tracking_url, data: { 'no-turbolink' => true }%>
        <span class="label label-info"><%=Tracking::Path.open_tracks.count%></span>
        <span class="label label-danger"><%=Tracking::Path.count%></span>
      </p>
    </div>
  </div>
  <div class="col-sm-6">
    <div>
      <h3 class="page-header">
        <i class="fa fa-cubes"></i>
        ობიექტები
      </h3>
      <div class="row">
        <div class="col-xs-6">
          <p>
            <i class="fa fa-building"></i>
            <%=link_to 'ოფისები', objects_offices_url%>
            <span class="label label-info"><%=Objects::Office.count%></span>
          </p>
          <p>
            <i class="fa fa-bolt"></i>
            <%=link_to 'ქვესადგურები', objects_substations_url%>
            <span class="label label-info"><%=Objects::Substation.count%></span>
          </p>
          <p>
            <i class="fa fa-bolt"></i>
            <%=link_to 'ანძები', objects_towers_url%>
            <span class="label label-info"><%=Objects::Tower.count%></span>
          </p>
        </div>
        <div class="col-xs-6">
          <p>
            <i class="fa fa-bolt"></i>
            <%=link_to 'გადამცემი ხაზები', objects_lines_url%>
            <span class="label label-info"><%=Objects::Line.count%></span>
          </p>
          <p>
            <i class="fa fa-road"></i>
            <%= link_to 'მარშუტები', objects_path_lines_url%>
            <span class="label label-info"><%=Objects::Path::Line.count%></span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render partial: 'layouts/admin' if sys_admin? %>

app/views/site/login.html.erb
<h2 class="page-header"><i class="fa fa-user"></i> <%=@title%></h2>
<%if @error.present?%>
<div class="alert alert-danger"><%=@error%></div>
<%end%>
<div class="row">
  <div class="col-sm-4">
    <%= form_tag request.url do %>
      <div class="form-group">
        <%=label_tag :username, t('models.sys_user.username')%>
        <%=text_field_tag :username, params[:username], autofocus:true, class:'form-control'%>
      </div>
      <div class="form-group">
        <%=label_tag :password, t('models.sys_user.password')%>
        <%=password_field_tag :password, params[:password], class:'form-control'%>
      </div>
      <div class="form-group">
        <%=submit_tag t('pages.site.login.action'), class:['btn','btn-primary']%>
      </div>
    <% end %>
  </div>
</div>